# Generated by Django 3.2.6 on 2022-06-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
